services:
  db:
    image: postgres
    container_name: ${database-name}

    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${database-name}
      POSTGRES_USER: ${database-user}
      POSTGRES_PASSWORD: ${database-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${database-pgadmin_default_email}
      PGADMIN_DEFAULT_PASSWORD: ${database-pgadmin_default_password}
    depends_on:
      - db
volumes:
  postgres_data:
