@apiKey = {{X_API_KEY}}
@campaignId = SAQRDEMSU



GET {{baseUrl}}/suggestions/activity/{{campaignId}}
X-API-KEY: {{apiKey}}


###

POST {{baseUrl}}/suggestions/activity/
X-API-KEY: {{apiKey}}

{
    "content": "HOliday in  nyc  Our anuall holiday isd comminh up please contribute on time an select you racbiities "
}