@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwiZW1haWwiOiJicmlnaHRAa3JvdHJ1c3QuY29tIiwiaGFuZGxlIjoiQlJLTFdSIiwiZXhwIjoxNzM1MTM3NDQ3fQ.r7rsPoN-4evxoAdM885_aYBrY9jrKqDRKTzztmoGImM

### Common Headers
@contentType = application/json
@apiKey = {{X_API_KEY}}
@ContributorID = 1
@ActivityID = 5
@campaignId = TRPNRUXPQ

@commentID = CMT697D5


### Create a new comment
POST {{baseUrl}}/activity/{{campaignId}}/{{ActivityID}}/comments
Content-Type: application/json
X-API-KEY: {{apiKey}}
Campaign-Key: {{campaignId}}
Authorization: Bearer {{authToken}}

{
    "content": "This is a test comment childe",
    "parentId":"CMT471D4"

}

### Update a specific comment
PATCH  {{baseUrl}}/activity/{{campaignId}}/{{ActivityID}}/comments/{{commentID}}
Content-Type: application/json
X-API-KEY: {{apiKey}}
Campaign-Key: {{campaignId}}
Authorization: Bearer {{authToken}}

{
    "content": "i wanna Upgrade: "
}

### Get all comments for an activity
GET {{baseUrl}}/activity/{{campaignId}}/{{ActivityID}}/comments
X-API-KEY: {{apiKey}}
Campaign-Key: {{campaignId}}
Authorization: Bearer {{authToken}}

### Get replies for a specific comment
GET {{baseUrl}}/activity/{{campaignId}}/{{ActivityID}}/comments/{{commentID}}/replies
X-API-KEY: {{apiKey}}
Campaign-Key: {{campaignId}}
Authorization: Bearer {{authToken}}

### Delete a specific comment
DELETE {{baseUrl}}/activity/{{campaignId}}/{{ActivityID}}/comments/{{commentID}}
X-API-KEY: {{apiKey}}
Campaign-Key: {{campaignId}}
Authorization: Bearer {{authToken}}

