### Environment Variables
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJicmlnaHRAa3JvdHJ1c3QuY29tIiwiaGFuZGxlIjoiQlJXUFlZIiwiZXhwIjoxNzM0NjkwODIyfQ.ttv62k3xQ7KenP7elsAGBetjIt-ECp3wY5QprJY96A4

### Common Headers
@contentType = application/json
@apiKey = {{X_API_KEY}}
@campaignId = SABWDMPTO


### Add Contributor to Campaign
POST {{baseUrl}}/contributor
Content-Type: {{contentType}}
X-API-KEY: {{apiKey}}
Authorization: Bearer {{authToken}}



### Update Contributor from Campaign
PATCH   {{baseUrl}}/contributor/{{campaignId}}/1
Content-Type: {{contentType}}
X-API-KEY: {{apiKey}}
Campaign-Key: {{campaignId}}
Authorization: Bearer {{authToken}}

{
    "name": "itsAhaman",
    "email": "itsAha@gmail.com"
}



### Remove Contributor from Campaign
DELETE  {{baseUrl}}/contributor/{{campaignId}}/2
Content-Type: {{contentType}}
X-API-KEY: {{apiKey}}
Campaign-Key: {{campaignId}}
Authorization: Bearer {{authToken}}



### Get Campaign contributors
GET  {{baseUrl}}/contributor/{{campaignId}}
Content-Type: {{contentType}}
X-API-KEY: {{apiKey}}
Campaign-Key: {{campaignId}}
Authorization: Bearer {{authToken}}



### Get contributor by ID
GET  {{baseUrl}}/contributor/{{campaignId}}/1
Content-Type: {{contentType}}
X-API-KEY: {{apiKey}}
Campaign-Key: {{campaignId}}
Authorization: Bearer {{authToken}}
